kookmin-sw/capstone-2022-06

- Assets/Resources/Animations/Anim_LichMinion.controller
- Assets/Resources/Animations/Anim_WorriorMinion.controller
- Assets/Resources/Prefabs/FootmanHP.prefab
- Assets/Resources/Prefabs/FreeLichHP.prefab
- Assets/Scripts/MinionScripts/LichMinion.cs
- Assets/Scripts/MinionScripts/MinionController.cs
- Assets/Scripts/MinionScripts/WorriorMinion.cs
- ProjectSettings/TagManager.asset
add minion ai for battle
see also : #6
> Add : Minion Battle AI

- .gitignore
- Assets/Resources/Materials.meta
- Assets/Resources/Materials/FogOfWar.mat
- Assets/Resources/Materials/FogOfWar.mat.meta
- Assets/Resources/Materials/ViewVisualisation.mat
- Assets/Resources/Materials/ViewVisualisation.mat.meta
- Assets/Resources/Textures.meta
- Assets/Resources/Textures/OpenFogTexture.renderTexture
- Assets/Resources/Textures/OpenFogTexture.renderTexture.meta
- Assets/Scripts/Character/FieldOfView.cs
- Assets/Scripts/Character/FieldOfView.cs.meta
- Assets/Scripts/ExLibrary.meta
- Assets/Scripts/ExLibrary/Geometry.cs
- Assets/Scripts/ExLibrary/Geometry.cs.meta
- Assets/Scripts/Field.meta
- Assets/Scripts/Field/FogProjector.cs
- Assets/Scripts/Field/FogProjector.cs.meta
- Assets/Shaders.meta
- Assets/Shaders/FogProjection.shader
- Assets/Shaders/FogProjection.shader.meta
- Assets/Shaders/GaussianBlur.shader
- Assets/Shaders/GaussianBlur.shader.meta
- ProjectSettings/TagManager.asset
AOS 게임의 핵심인 전장의 안개 기능에 필요한 코드 작성을 마무리
관련 이슈 : #19
> Feature/19 전장의 안개 기반 코드 작성

- Assets/Scenes/ScoreBoard.unity
- Assets/Scenes/ScoreBoard.unity.meta
> Add : ScoreBoard UI Scene

- README.md
- docs/index.md
> [변경] 제목 변경

- Assets/Resources/Animations/Anim_LichMinion.controller
- Assets/Resources/Prefabs/Bullet.prefab
- Assets/Resources/Prefabs/Bullet.prefab.meta
- Assets/Resources/Prefabs/FootmanHP.prefab
- Assets/Resources/Prefabs/FreeLichHP.prefab
- Assets/Scripts/MinionScripts/LichBullet.cs
- Assets/Scripts/MinionScripts/LichBullet.cs.meta
- Assets/Scripts/MinionScripts/LichMinion.cs
- Assets/Scripts/MinionScripts/MinionController.cs
- Assets/Scripts/MinionScripts/MinionStat.cs
- Assets/Scripts/MinionScripts/WorriorMinion.cs
마법사 미니언에 총알 생성 기능을 추가하고 데미지를 입히는 기능도 추가하였다. 그리고 개발 중 이미 죽은 미니언을 한동안 계속해서 타겟팅하는 이슈가 발생하여 이 또한 WorriorMinion, LichMinion 에서 해결함
see also: #44
> Add LichBullet

- Assets/Scenes/GameScene.unity
- Assets/Scenes/Old.unity
- Assets/Scenes/Old.unity.meta
게임 씬 구축과 챔피언 더미 프리팹 추가
관련 이슈 : #53
> [추가] 게임 씬 구축과 챔피언 더미 프리팹 추가

- Assets/Scenes/GameScene.unity
GameScene 클래스 부여를 위해 @Scene 오브젝트를 생성하고 산하 컴포넌트로 GameScene 부착
관련 이슈 : #56
> [변경] @Scene 오브젝트 추가

- Assets/Resources/Prefabs/UI/Scene/UI_Lobby.prefab
- Assets/Resources/Prefabs/UI/SubItem/UI_CancelButton.prefab
- Assets/Resources/Prefabs/UI/SubItem/UI_ConfirmButton.prefab
- Assets/Scripts/UI/Scene/UI_Lobby.cs
- Assets/Scripts/UI/Scene/UI_Preparation.cs
다 모이지 않았음에도 불구하고 PreparationScene을 load하는 문제를 해결
관련 이슈 : #59
> Issue/59 혼자서 게임에 입장하는 문제 해결

- Assets/Resources/Prefabs/UI/Scene/UI_GameScene.prefab
- Assets/Scenes/GameScene.unity
- Assets/Scripts/Scenes/GameScene.cs
- Assets/Scripts/UI/Scene/UI_GameScene.cs
- Assets/Scripts/UI/Scene/UI_GameScene.cs.meta
- Assets/Scripts/UI/Scene/UI_Preparation.cs
이제 GameScene에 들어가면 우상단 패널에 게임 경과 시간을 보여줍니다.
관련 이슈 : #68
> Feature/68 게임 경과 시간을 보여주는 UI 구현

- Assets/Scripts/Scenes/GameScene.cs
게임 씬을 로드할 때 스폰 위치를 지정하는 코드를 작성했습니다. 이는 지휘관의 카메라 위치도 포함입니다.
관련 이슈 : #63
> Feature/63 스폰 위치를 지정하는 코드 작성

- Assets/Scripts/Character/ClickMovement.cs
- Assets/Scripts/Character/PlayerHealthSlider.cs
- Assets/Scripts/Commander.meta
- Assets/Scripts/Commander/CommanderCamController.cs
- Assets/Scripts/Commander/CommanderCamController.cs.meta
- Assets/Scripts/Scenes/GameScene.cs
챔피언이면 카메라를 Photon intantiate 된 자기 챔피언을 따라다니도록 합니다.
지휘관이면 자유롭게 이동할 수 있도록 합니다. 단, 맵 밖을 벗어나게 하지 않습니다.
> Feature/76 챔피언, 지휘관 구분에 따른 카메라 이동 기능 구현

- Assets/Scenes/Character.unity
- Assets/Scripts/Character/Ability.cs
- Assets/Scripts/Character/Stats.cs
레벨업을 할 때마다 스킬포인트 1씩 부여되어 스킬포인트로 스킬 레벨을 올릴 수 있음
스킬포인트를 찍기 전에는 스킬사용이 불가능하고 6레벨 전에는 R을 찍을 수 없음
관련 이슈 : #67
> [추가] 챔피언 스킬포인트 로직 추가

- Assets/Scripts/Character/LayerController.cs
- Assets/Scripts/ExLibrary/Util.cs
- Assets/Scripts/MinionScripts/WaveManager.cs
- Assets/Scripts/Scenes/GameScene.cs
> Issue/93 전장의 안개 완벽 픽스

- Assets/Scenes/Character.unity
Character씬의 Mangoawl(Dummy)에서 Mangoawl(0516)으로 이름변경
관련 이슈 : #107
> [변경]Character씬의 Mangoawl(Dummy)에서 Mangoawl(0516)으로 이름변경

- Assets/Resources/Prefabs/Camera/Game/BirdEyeView.prefab
- Assets/Resources/Prefabs/UI/WorldSpace/UI_AreaIndicator.prefab
- Assets/Resources/Prefabs/UI/WorldSpace/UI_AreaIndicator.prefab.meta
- Assets/Scenes/GameScene.unity
- Assets/Scripts/Particle.meta
- Assets/Scripts/Particle/LeavesBuff.cs
- Assets/Scripts/Particle/LeavesBuff.cs.meta
- Assets/Scripts/Particle/Meteor.cs
- Assets/Scripts/Particle/Meteor.cs.meta
- Assets/Scripts/Particle/ParticleBase.cs
- Assets/Scripts/Particle/ParticleBase.cs.meta
- Assets/Scripts/UI/Effect/UI_Cooldown.cs
- Assets/Scripts/UI/Scene/UI_Preparation.cs
- Assets/Scripts/UI/SubItem/UI_ChampSkill.cs
- Assets/Scripts/UI/SubItem/UI_ComSkill.cs
- Assets/Scripts/UI/WorldSpace/UI_AreaIndicator.cs
- Assets/Scripts/UI/WorldSpace/UI_AreaIndicator.cs.meta
- ProjectSettings/TagManager.asset
지휘관 UI가 잘 작동합니다.
스킬 2종류를 호출할 수 있습니다.
데미지를 입히거나 치유하는 것에 대해선 스탯 이슈와 관련되어 잠시 보류하도록 합니다.
> Feature/103 지휘관 UI 구현 및 스킬 호출 구현 완료

- Assets/Scenes/Lobby/PreparationScene.unity
- Assets/Scripts/Define/Stats/ObjectStat.cs
- Assets/Scripts/ExLibrary/Util.cs
- Assets/Scripts/Particle/LeavesBuff.cs
- Assets/Scripts/Particle/Meteor.cs
- Assets/Scripts/Particle/ParticleBase.cs
- Assets/Scripts/UI/Effect/UI_Cooldown.cs
이제 지휘관은 아군 미니언에게 치유 효과를 주거나 적 미니언을 공격할 수 있습니다.
추후 챔피언의 문제가 해결되었음에도 불구하고 챔피언에게 적용되지 않으면 새로운 이슈를 부여해 처리할 예정입니다.
> Feature/117 지휘관 기능 구현(미니언 한정)

- Assets/Resources/Data/HeroIcons.json
- Assets/Resources/Data/SkillIcons.meta
- Assets/Resources/Data/SkillIcons/MangoawlSkills.json
- Assets/Resources/Data/SkillIcons/MangoawlSkills.json.meta
- Assets/Resources/Prefabs/UI/SubItem/UI_ChampSkill.prefab
- Assets/Scripts/Character/Ability.cs
- Assets/Scripts/Character/Health.cs
- Assets/Scripts/Data/PortraitButtonData.cs
- Assets/Scripts/ExLibrary/Util.cs
- Assets/Scripts/UI/Scene/UI_Preparation.cs
- Assets/Scripts/UI/SubItem/UI_ChampSkill.cs
구현이 급하므로 성능의 불이익을 보더라도 Util.SearchChild를 사용하여 필요한 컴포넌트를 동적으로 할당했습니다.
챔피언 스킬의 네트워킹에 대해선 다음에 다시 생각하도록 합니다.
> Feature/125 챔피언 UI 최신화 완료

- Assets/Scripts/Character/Ability.cs
- Assets/Scripts/Character/THSSkill_EProj.cs
- Assets/Scripts/Character/THSSkill_RProj.cs
챔피언 스킬이 포톤 환경에서 작동되도록 변경
관련 이슈 : #127
> Feature/127 챔피언 스킬이 포톤 환경에서 작동되도록 변경

- Assets/Scripts/Character/Ability.cs
E 스킬이 이상한 곳으로 날아가지 않도록 변경
관련 이슈 : #137
> [변경] E 스킬 궤적 안정화

- Assets/Scripts/Character/CameraRoam.cs
- Assets/Scripts/Scenes/GameScene.cs
CameraRoam에서 player를 할당받지 못하는 에러 수정
관련 이슈 : #149
> [수정] CameraRoam에서 player를 할당받지 못하는 에러 수정

- Assets/Resources/Animations/Anim_Character_THS.controller
- Assets/Scripts/Character/ChampionManager.cs
챔피언 사망 애니메이션 추가, hp리젠 수치 수정
관련 이슈 : #151
> [추가, 수정] 챔피언 사망 애니메이션 추가, hp리젠 수치 수정

- Assets/Resources/Prefabs/UI/Scene/UI_DeadPanel.prefab
- Assets/Resources/Prefabs/UI/Scene/UI_DeadPanel.prefab.meta
- Assets/Scripts/Character/Ability.cs
- Assets/Scripts/Character/ChampionManager.cs
- Assets/Scripts/Character/ClickMovement.cs
- Assets/Scripts/Character/THSSkill_EProj.cs
- Assets/Scripts/Character/THSSkill_RProj.cs
- Assets/Scripts/Define/Stats/ObjectStat.cs
- Assets/Scripts/MinionScripts/MinionController.cs
- Assets/Scripts/Turret/TurretController.cs
- Assets/Scripts/UI/Scene/UI_DeadPanel.cs
- Assets/Scripts/UI/Scene/UI_DeadPanel.cs.meta
사망할 떄 사망했음을 알려주는 UI를 출력하고 움직이지 못하도록 했습니다.
> Feature/155 사망할 때 UI 출력

- Assets/Resources/Data/HeroIcons.json
사용 가능한 영웅만 뜨도록 변경
관련 이슈 : #157
> [변경] 영웅 목록 데이터 정리

- Assets/Resources/Particle/FireExplosionEffects/Materials/SmokeDarkParticle.mat
- Assets/Scenes/Lobby/LobbyScene.unity
- Assets/Scenes/Lobby/PreparationScene.unity
- Assets/Scripts/Scenes/GameScene.cs
> Issue/147 E, R 스킬 사운드 및 BGM 배치 완료

- Assets/Scripts/Character/LayerController.cs
> Issue/148 포탑에 FOV 부착

- Assets/Scripts/MinionScripts/MinionController.cs
미니언이 사망 시 본인이 주는 경험치에서 주변의 상대팀 플레이어의 수를 나눈 만큼 경험치 부여
see also : #161
> [변경] MinionController.cs 미니언 경험치 부여

- Assets/Scripts/Character/ChampionManager.cs
챔피언 성장 능력치 추가, 리스폰 애니메이션 수정
관련 이슈 : #164
> [추가, 수정] 챔피언 성장 능력치 추가, 리스폰 애니메이션 수정

- Assets/Resources/Prefabs/UI/Scene/UI_Lobby.prefab
- Assets/Resources/Prefabs/UI/SubItem/UI_ExitMenuPopup.prefab
- Assets/Resources/Prefabs/UI/SubItem/UI_ExitMenuPopup.prefab.meta
- Assets/Scripts/UI/Scene/UI_GameScene.cs
- Assets/Scripts/UI/Scene/UI_Lobby.cs
- Assets/Scripts/UI/SubItem/UI_ExitMenuPopup.cs
- Assets/Scripts/UI/SubItem/UI_ExitMenuPopup.cs.meta
이제 편하게 게임을 종료할 수 있습니다.
관련 이슈 : #166
> Feature/166 게임 종료 UI 구현

- Assets/Scripts/MinionScripts/MinionController.cs
애니메이션 동작 오류 해결
see also : #168
> [변경] MinionController.cs 애니메이션 동작오류 해결
